name: Validate llms-full.txt

on:
  workflow_call:
    inputs:
      llms_script_path:
        required: false
        type: string
        default: ".github/scripts/llms-scripts/generate_llms.py"
      llms_file_name:
        required: false
        type: string
        default: "llms-full.txt"

jobs:
  check-llms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests beautifulsoup4

      - name: Get SHA256 hash of the PR's ${{ inputs.llms_file_name }}
        id: pr_llms_hash
        run: |
          if [ -f "${{ inputs.llms_file_name }}" ]; then
            sha256sum "${{ inputs.llms_file_name }}" | awk '{ print $1 }' > pr_sha256.txt
          else
            echo "0000" > pr_sha256.txt
          fi
          cat pr_sha256.txt

      - name: Generate ${{ inputs.llms_file_name }} using script
        run: python3 ${{ inputs.llms_script_path }}

      - name: Calculate SHA256 hash of the generated file
        id: generated_llms_hash
        run: |
          llms_file="${{ github.workspace }}/${{ inputs.llms_file_name }}"

          if [ -f "$llms_file" ]; then
            sha256sum "$llms_file" | awk '{ print $1 }' > generated_sha256.txt
          else
            echo "Error: $llms_file not found"
            exit 1
          fi
          cat generated_sha256.txt

      - name: Compare the SHA256 hashes
        run: |
          generated_hash=$(cat generated_sha256.txt)
          pr_hash=$(cat pr_sha256.txt)

          if [ "$generated_hash" != "$pr_hash" ]; then
            echo "Error: SHA256 hashes do not match. The generated ${{ inputs.llms_file_name }} file differs from the one in the PR."
            echo "You need to run the generate LLMS script:"
            echo "python3 ${{ inputs.llms_script_path }}"
            exit 1
          else
            echo "SHA256 hashes match. The file is consistent."
          fi
