name: Use Check MkDocs Build

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      mkdocs_repo:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: main
    secrets:
      REPO_SCOPED_TOKEN:
        required: true

jobs:
  build-docs-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo (docs repo)
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'

      - name: Allow moving dotfiles
        run: |
          shopt -s dotglob

      - name: Clone MKDocs Repo
        run: |
          git clone https://${{ secrets.REPO_SCOPED_TOKEN }}@github.com/${{ inputs.mkdocs_repo }}.git mkdocs-repo

      - name: Prepare content directory inside MKDocs repo
        run: |
          cd mkdocs-repo

          # Determine content folder name (kluster uses 'docs', others use <repo_name>-docs)
          if [[ "${{ inputs.repo_name }}" == "kluster" ]]; then
            CONTENT_DIR="docs"
          else
            CONTENT_DIR="${{ inputs.repo_name }}-docs"
          fi

          mkdir -p "$CONTENT_DIR"
          cd ..

          # Move content into the correct subfolder
          find . -mindepth 1 -maxdepth 1 ! -name 'mkdocs-repo' -exec mv {} mkdocs-repo/$CONTENT_DIR/ \;

      - name: Install pip requirements
        run: |
          cd mkdocs-repo
          pip install --upgrade pip setuptools==65.7.0
          pip install mistune==3.0.2  # Pin until https://github.com/lepture/mistune/issues/403 resolved
          pip install -r requirements.txt &> /dev/null && echo "Dependencies installed" || echo "Error while installing dependencies"

      - name: Build MkDocs site
        run: |
          cd mkdocs-repo
          sed -i 's/site_dir.*/site_dir: site/' mkdocs.yml
          mkdocs build
