# In: Telucero/workflows/.github/workflows/mkdocs-build.yml

name: MkDocs Build

on:
  workflow_call:
    inputs:
      mkdocs_repo:
        required: true
        type: string
      docs_dir:
        required: true
        type: string
      needs_mistune:  # New input added
        required: false   # You can make it optional if you don't always need it
        type: boolean     # Treat it as a boolean input
    secrets:
      token:
        required: true

jobs:
  build-docs-site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'

      - name: Enable dotglob to include dotfiles
        run: shopt -s dotglob

      - name: Clone MkDocs Repository
        run: |
          echo "Cloning: ${{ inputs.mkdocs_repo }}"
          git clone https://${{ secrets.token }}@github.com/${{ inputs.mkdocs_repo }} mkdocs-repo

      - name: Copy Docs Content into MkDocs Repo
        if: ${{ inputs.docs_dir != 'wormhole-docs' }}
        run: |
          mkdir mkdocs-repo/${{ inputs.docs_dir }}
          find . -mindepth 1 -maxdepth 1 ! -name 'mkdocs-repo' -exec mv {} mkdocs-repo/${{ inputs.docs_dir }}/ \;

      - name: Update Submodule for Wormhole
        if: ${{ inputs.docs_dir == 'wormhole-docs' }}
        run: git submodule update --remote

      - name: Install Python Requirements
        run: |
          cd mkdocs-repo
          pip3 install --upgrade pip setuptools==65.7.0
          # Install mistune if needs_mistune is true
          if [[ "${{ inputs.needs_mistune }}" == "true" ]]; then
            pip3 install mistune==3.0.2
          fi
          pip3 install -r requirements.txt &> /dev/null || echo "Dependency install failed"

      - name: Build MkDocs Site
        run: |
          cd mkdocs-repo
          sed -i 's/site_dir.*/site_dir: site/' mkdocs.yml
          python3 -m mkdocs build
